version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: simqueue_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fila_sistema
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - simqueue-dev

  postgres-test:
    image: postgres:17
    container_name: simqueue_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fila_sistema_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - simqueue-dev

  api:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    container_name: simqueue_api_dev
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/fila_sistema"
      DATABASE_URL_TEST: "postgresql://postgres:postgres@postgres-test:5432/fila_sistema_test"
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - simqueue-dev
    volumes:
      - ../../:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  pgdata_dev:
  pgdata_test:

networks:
  simqueue-dev:
    driver: bridge