version: '3.9'

services:
  postgres-prod:
    image: postgres:17
    container_name: postgres_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fila_sistema
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  postgres-test:
    image: postgres:17
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fila_sistema_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_prod:
  pgdata_test:
