-- CreateEnum
CREATE TYPE "public"."QueueStatus" AS ENUM ('WAITING', 'ACTIVE', 'CONFIRMED', 'MISSED', 'COMPLETED');

-- AlterTable
ALTER TABLE "public"."Queue" ADD COLUMN "confirmedAt" TIMESTAMP(3),
ADD COLUMN "expiresAt" TIMESTAMP(3),
ADD COLUMN "missedTurns" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "status" "public"."QueueStatus" NOT NULL DEFAULT 'WAITING',
ADD COLUMN "totalWaitTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "turnStartAt" TIMESTAMP(3),
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
